name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: ls -a ${{ github.workspace }}
      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: -avzr #"-rltgoDzvO"
          SOURCE: "."
          REMOTE_HOST: dvoell.online
          REMOTE_USER: lap-manul
          TARGET: '/home/lap-manul/deploy/'
          EXCLUDE: ".git/, /node_modules/"
      - name: restart server
        run: |
          sudo cat <<EOT > /lib/systemd/system/dvoell-online.service
          [Unit]
          Description=dvoell.online service
          [Service]
          Type=simple
          WorkingDirectory=/home/lap-manul/deploy
          ExecStart=/usr/local/bin/nodemon app.js
          [Install]
          WantedBy=multi-user.target
          EOT
          sudo systemctl daemon-reload
          sudo systemctl enable dvoell-online
          sudo systemctl start dvoell-online
      - run: echo "🍏 This job's status is ${{ job.status }}."